### ISSUE TITLE
Redeem及Addlicense等命令在asf新版本上无法使用

### ISSUE THREAD

**Issue by zhongfly** [deluxghost/ASF_IPC#2]
发送如‘redeem asf 2777’之类的命令后，asf返回‘未知命令’。其他不带参数的命令如version，无问题。
而使用IPC GUI，发送同样命令，asf不会提示未知命令

9.7日时能正常使用，可能是最近的更新修改了相关API？

**Comment by zhongfly** [comment]
asf版本3.3.0.9
asf_ipc版本 1.2.0

**Comment by deluxghost** [comment]
前几天发现这个我没注意
刚才看api应该没什么改动，晚些时候我来测试一下再说

**Comment by deluxghost** [comment]
测试其他命令没有问题（2fa，status等），所以API没问题。应该是redeem和addlicense命令的问题，或者可能某版本需要进一步的配置，建议去discord问一下asf作者，然后麻烦您在这里回复反馈一下

**Comment by zhongfly** [comment]
我看了一遍代码，43行存在问题，urlparse.quote_plus把命令中的空格全部变成了加号，即'redeem asf 123'变成了'redeem+asf+1234'

**Comment by deluxghost** [comment]
这是标准的url encode啊...我测试status bot之类的命令是没问题的，但是用curl测试redeem也有问题
edit: 好像asf确实不认加号了（
那么可以把quote_plus改成quote

**Comment by deluxghost** [comment]
fixed
